"""
process.py — Convert a scientific PDF into LLM-readable Markdown.

Images and figures are replaced with detailed textual descriptions
generated by a vision model (Gemini Flash or local Gemma 4), so the
final markdown is fully understandable by text-only LLMs.

Usage:
    python process.py input.pdf
    python process.py input.pdf -o output.md
    python process.py input.pdf --local          # offline, no API key

Requires:
    pip install docling google-genai
    Set GEMINI_API_KEY environment variable (not needed with --local).
"""

import argparse
import os
import re
import sys
import time
from pathlib import Path

from dotenv import load_dotenv

from docling.datamodel.base_models import ConversionStatus, InputFormat
from docling.datamodel.pipeline_options import PdfPipelineOptions
from docling.document_converter import DocumentConverter, PdfFormatOption
from docling_core.types.doc import ImageRefMode, PictureItem

import io

try:
    from google import genai
    from google.genai import types
except ImportError:
    genai = None
    types = None

GEMINI_MODEL = "gemini-2.5-flash"

LOCAL_HF_REPO = "ggml-org/gemma-4-E4B-it-GGUF"
LOCAL_MODEL_FILE = "gemma-4-E4B-it-Q4_K_M.gguf"
LOCAL_MMPROJ_FILE = "mmproj-gemma-4-E4B-it-Q8_0.gguf"

IMAGE_PROMPT = """\
You are analyzing a figure extracted from a scientific research paper.
Your task is to describe this figure so that someone who cannot see it
fully understands the data, trends, and conclusions it conveys.

## Surrounding context from the paper:

{context}

## Instructions:

- State what type of figure this is (bar chart, line graph, microscopy image, \
schematic diagram, flow chart, photograph, etc.)
- Describe axes, labels, legends, and scales if applicable
- Report key data points, trends, and patterns — be quantitative (include \
numbers, units, comparisons) where the figure allows it
- Note statistical indicators if visible (error bars, significance markers, \
p-values, confidence intervals)
- Explain what scientific conclusion the figure supports, based on the context
- Keep the description concise but complete — typically 3-8 sentences
"""


# ---------------------------------------------------------------------------
# PDF parsing
# ---------------------------------------------------------------------------

def _make_pipeline_options(generate_images: bool = True, images_scale: float = 2.0):
    """Build memory-optimized PdfPipelineOptions."""
    opts = PdfPipelineOptions()
    opts.generate_picture_images = generate_images
    opts.images_scale = images_scale
    opts.generate_parsed_pages = False   # Free page data after processing
    opts.generate_page_images = False
    opts.generate_table_images = False
    opts.document_timeout = 600
    return opts


def convert_pdf(pdf_path: Path):
    """Parse a PDF with Docling, extracting figure images.

    Strategy:
    1. Try default docling-parse backend with memory-optimized settings.
    2. If errors occur (std::bad_alloc), retry with pypdfium2 backend
       which bypasses the buggy C++ parser entirely.
    """
    # --- Attempt 1: default backend, optimized settings ---
    opts = _make_pipeline_options(generate_images=True, images_scale=2.0)
    converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(pipeline_options=opts),
        }
    )
    result = converter.convert(str(pdf_path), raises_on_error=False)

    if result.status == ConversionStatus.SUCCESS:
        return result.document

    n_errors = len(result.errors) if result.errors else 0
    print(
        f"  Default backend had {n_errors} error(s), retrying with pypdfium2 backend...",
        file=sys.stderr,
    )

    # --- Attempt 2: pypdfium2 backend (bypasses C++ docling-parse) ---
    from docling.backend.pypdfium2_backend import PyPdfiumDocumentBackend
    opts = _make_pipeline_options(generate_images=True, images_scale=1.5)
    converter = DocumentConverter(
        format_options={
            InputFormat.PDF: PdfFormatOption(
                pipeline_options=opts,
                backend=PyPdfiumDocumentBackend,
            ),
        }
    )
    result = converter.convert(str(pdf_path), raises_on_error=False)

    if result.status == ConversionStatus.SUCCESS:
        print(f"  pypdfium2 backend succeeded.", file=sys.stderr)
        return result.document

    n_errors = len(result.errors) if result.errors else 0
    if result.status == ConversionStatus.PARTIAL_SUCCESS:
        print(
            f"  pypdfium2 partial conversion ({n_errors} error(s)) — using available content.",
            file=sys.stderr,
        )
        return result.document

    raise RuntimeError(
        f"PDF conversion failed on both backends ({n_errors} error(s))"
    )


def extract_images(document):
    """Collect PIL images from PictureItems in document order."""
    images = []
    for item, _level in document.iterate_items():
        if isinstance(item, PictureItem):
            images.append(item.image)  # PIL Image or None
    return images


# ---------------------------------------------------------------------------
# Context building — operates on the exported markdown string
# ---------------------------------------------------------------------------

def _find_section_bounds(lines, header_indices, target_line):
    """Find the start/end line indices of the section containing target_line."""
    section_start = 0
    section_level = 0

    for si in header_indices:
        if si <= target_line:
            section_start = si
            match = re.match(r"^(#{1,6})\s", lines[si])
            section_level = len(match.group(1)) if match else 0
        else:
            break

    section_end = len(lines)
    for si in header_indices:
        if si > target_line:
            match = re.match(r"^(#{1,6})\s", lines[si])
            level = len(match.group(1)) if match else 99
            if level <= section_level:
                section_end = si
                break

    return section_start, section_end


def _find_figure_id(lines, placeholder_line):
    """Look near a placeholder for a 'Figure N' / 'Fig. N' identifier."""
    for offset in range(1, 5):
        for delta in (offset, -offset):
            idx = placeholder_line + delta
            if 0 <= idx < len(lines):
                match = re.search(
                    r"(?:Figure|Fig\.?)\s*(\d+)", lines[idx], re.IGNORECASE
                )
                if match:
                    return match.group(0)
    return None


def _find_external_references(lines, figure_id, exclude_start, exclude_end):
    """Find paragraphs outside the section that mention the figure."""
    pattern = re.compile(re.escape(figure_id), re.IGNORECASE)
    refs = []
    for i, line in enumerate(lines):
        if exclude_start <= i < exclude_end:
            continue
        if pattern.search(line):
            ctx_start = max(0, i - 1)
            ctx_end = min(len(lines), i + 2)
            refs.append("\n".join(lines[ctx_start:ctx_end]))
    return refs


PLACEHOLDER = "<!-- image -->"


def build_contexts(markdown: str) -> list[str]:
    """Build a context string for every image placeholder in the markdown."""
    lines = markdown.split("\n")

    header_indices = [
        i for i, line in enumerate(lines) if re.match(r"^#{1,6}\s", line)
    ]
    placeholder_lines = [
        i for i, line in enumerate(lines) if PLACEHOLDER in line
    ]

    contexts = []
    for pl in placeholder_lines:
        sec_start, sec_end = _find_section_bounds(lines, header_indices, pl)

        # Gather section text, excluding the placeholder itself
        section_text = "\n".join(
            line
            for i, line in enumerate(lines[sec_start:sec_end])
            if (i + sec_start) != pl and PLACEHOLDER not in line
        ).strip()

        # Search for "Figure N" references outside this section
        figure_id = _find_figure_id(lines, pl)
        extra = ""
        if figure_id:
            refs = _find_external_references(
                lines, figure_id, sec_start, sec_end
            )
            if refs:
                extra = (
                    "\n\nAdditional references to this figure elsewhere in "
                    "the paper:\n\n" + "\n---\n".join(refs)
                )

        contexts.append(section_text + extra)

    return contexts


# ---------------------------------------------------------------------------
# Local vision model (Gemma 4 via llama-cpp-python)
# ---------------------------------------------------------------------------

def _init_local_model():
    """Download GGUF files and create a local multimodal Llama instance."""
    try:
        from llama_cpp import Llama
        from llama_cpp.llama_chat_format import Llava15ChatHandler
    except ImportError:
        print(
            "Error: llama-cpp-python is required for --local mode.\n"
            "  pip install llama-cpp-python",
            file=sys.stderr,
        )
        sys.exit(1)

    try:
        from huggingface_hub import hf_hub_download
    except ImportError:
        print(
            "Error: huggingface-hub is required for --local mode.\n"
            "  pip install huggingface-hub",
            file=sys.stderr,
        )
        sys.exit(1)

    print("  Downloading model files (cached after first run)...", file=sys.stderr)
    model_path = hf_hub_download(repo_id=LOCAL_HF_REPO, filename=LOCAL_MODEL_FILE)
    mmproj_path = hf_hub_download(repo_id=LOCAL_HF_REPO, filename=LOCAL_MMPROJ_FILE)

    chat_handler = Llava15ChatHandler(clip_model_path=mmproj_path)
    llm = Llama(
        model_path=model_path,
        chat_handler=chat_handler,
        n_ctx=4096,
        n_batch=2048,
        n_gpu_layers=-1,
    )
    return llm


def _image_to_data_uri(image) -> str:
    """Convert a PIL image to a base64 PNG data URI."""
    import base64
    pil = image.pil_image if hasattr(image, "pil_image") else image
    buf = io.BytesIO()
    pil.save(buf, format="PNG")
    b64 = base64.b64encode(buf.getvalue()).decode("utf-8")
    return f"data:image/png;base64,{b64}"


def describe_image_local(llm, image, context: str) -> tuple[str, bool]:
    """Describe an image using a local multimodal model."""
    prompt = IMAGE_PROMPT.format(
        context=context or "(No surrounding context available)"
    )
    data_uri = _image_to_data_uri(image)
    try:
        response = llm.create_chat_completion(
            messages=[
                {
                    "role": "user",
                    "content": [
                        {"type": "image_url", "image_url": {"url": data_uri}},
                        {"type": "text", "text": "Do not think.\n\n" + prompt},
                    ],
                }
            ],
            max_tokens=1024,
        )
        text = response["choices"][0]["message"]["content"]
        if not text or not text.strip():
            return "[WARNING: Local model returned an empty description for this image]", False
        return text.strip(), True
    except Exception as e:
        print(f"    Error: {e}", file=sys.stderr)
        return f"[WARNING: Image interpretation failed — {e}]", False


# ---------------------------------------------------------------------------
# Gemini vision model
# ---------------------------------------------------------------------------

def _image_to_part(image) -> "types.Part":
    """Convert a docling ImageRef or PIL Image to a Gemini Part."""
    pil = image.pil_image if hasattr(image, "pil_image") else image
    buf = io.BytesIO()
    pil.save(buf, format="PNG")
    return types.Part.from_bytes(data=buf.getvalue(), mime_type="image/png")


MAX_RETRIES = 5
RETRY_BASE_DELAY = 5  # seconds


def describe_image(client, model: str, image, context: str) -> tuple[str, bool]:
    """Send an image + context to Gemini. Returns (description, success)."""
    prompt = IMAGE_PROMPT.format(
        context=context or "(No surrounding context available)"
    )
    part = _image_to_part(image)
    for attempt in range(MAX_RETRIES):
        try:
            response = client.models.generate_content(
                model=model,
                contents=[part, prompt],
            )
            text = response.text
            if not text or not text.strip():
                return "[WARNING: Vision model returned an empty description for this image]", False
            return text, True
        except Exception as e:
            status = getattr(e, "status_code", None) or getattr(e, "code", 0)
            if status in (429, 503) and attempt < MAX_RETRIES - 1:
                delay = RETRY_BASE_DELAY * (2 ** attempt)
                print(
                    f"    Rate limited, retrying in {delay}s...",
                    file=sys.stderr,
                )
                time.sleep(delay)
            elif attempt < MAX_RETRIES - 1:
                print(
                    f"    Error: {e}, retrying...",
                    file=sys.stderr,
                )
                time.sleep(RETRY_BASE_DELAY)
            else:
                print(
                    f"    Error: failed after {MAX_RETRIES} attempts: {e}",
                    file=sys.stderr,
                )
                return f"[WARNING: Image interpretation failed — {e}]", False


# ---------------------------------------------------------------------------
# Orchestration
# ---------------------------------------------------------------------------

def process(pdf_path: Path, model: str, api_key: str = None, local_llm=None) -> str:
    """Full pipeline: PDF → Markdown with interpreted figures."""
    # Step 1 — parse PDF
    print("  Parsing PDF with Docling...", file=sys.stderr)
    document = convert_pdf(pdf_path)

    # Step 2 — collect images (PIL objects, in document order)
    images = extract_images(document)

    # Step 3 — export markdown with placeholders
    markdown = document.export_to_markdown(image_mode=ImageRefMode.PLACEHOLDER)

    if not images:
        print("  No images found in document.", file=sys.stderr)
        return markdown

    # Step 4 — build context for each placeholder from the markdown text
    contexts = build_contexts(markdown)

    if len(contexts) != len(images):
        print(
            f"  Warning: found {len(images)} images but {len(contexts)} "
            f"placeholders — some images may be mis-aligned.",
            file=sys.stderr,
        )

    # Step 5 — describe each image with the vision model
    client = None
    if local_llm is None:
        client = genai.Client(api_key=api_key)
    descriptions: list[str] = []
    warnings: list[str] = []

    for i, (image, context) in enumerate(zip(images, contexts), start=1):
        if image is None:
            msg = f"Image {i}: could not be extracted from PDF"
            print(f"  Warning: {msg}", file=sys.stderr)
            warnings.append(msg)
            descriptions.append("[WARNING: Image could not be extracted from PDF]")
            continue

        print(f"  Interpreting image {i}/{len(images)}...", file=sys.stderr)
        if local_llm is not None:
            desc, success = describe_image_local(local_llm, image, context)
        else:
            desc, success = describe_image(client, model, image, context)
        if not success:
            msg = f"Image {i}: interpretation failed"
            print(f"  Warning: {msg}", file=sys.stderr)
            warnings.append(msg)
        descriptions.append(desc)

    # Step 6 — replace placeholders with formatted descriptions
    for i, desc in enumerate(descriptions, start=1):
        block = _format_description(i, desc)
        markdown = markdown.replace(PLACEHOLDER, block, 1)

    if warnings:
        print(
            f"  Completed with {len(warnings)} warning(s):",
            file=sys.stderr,
        )
        for w in warnings:
            print(f"    - {w}", file=sys.stderr)

    return markdown


def _format_description(figure_num: int, description: str) -> str:
    """Wrap a description as a clearly-marked interpreted-figure block."""
    header = f"> **[Interpreted Image {figure_num}]**"
    body_lines = []
    for line in description.strip().split("\n"):
        body_lines.append(f"> {line}" if line.strip() else ">")
    return header + "\n" + "\n".join(body_lines)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    load_dotenv()

    parser = argparse.ArgumentParser(
        description=(
            "Convert a scientific PDF to LLM-readable Markdown "
            "with interpreted figures."
        )
    )
    parser.add_argument("pdf", type=Path, help="Path to the input PDF file")
    parser.add_argument(
        "-o", "--output", type=Path, help="Output markdown file path"
    )
    parser.add_argument(
        "--model",
        default=GEMINI_MODEL,
        help=f"Gemini model name (default: {GEMINI_MODEL})",
    )
    parser.add_argument(
        "--local",
        action="store_true",
        help="Use local Gemma 4 model instead of Gemini API (no API key needed)",
    )
    args = parser.parse_args()

    if not args.pdf.exists():
        print(f"Error: file not found: {args.pdf}", file=sys.stderr)
        sys.exit(1)

    local_llm = None
    api_key = None

    if args.local:
        local_llm = _init_local_model()
    else:
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            print(
                "Error: set the GEMINI_API_KEY environment variable "
                "(or use --local for offline mode).",
                file=sys.stderr,
            )
            sys.exit(1)

    output_path = args.output or args.pdf.with_suffix(".md")

    print(f"Processing: {args.pdf}", file=sys.stderr)
    markdown = process(args.pdf, args.model, api_key=api_key, local_llm=local_llm)

    output_path.write_text(markdown, encoding="utf-8")
    print(f"Done → {output_path}", file=sys.stderr)


if __name__ == "__main__":
    main()
